accounts/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
]

profiles/urls.py
from django.conf.urls import url, include


from . import views


urlpatterns = [
    url(r'^me/applications/(?P<position>\d+)/(?P<applicant>\d+)/(?P<status>\w+)/$',
        views.UserApplicationStatus.as_view(), name='status_update'),
    url(r'^me/applications/$', views.UserApplications.as_view(), name='my_applications'),
    url(r'^me/edit/$', views.EditProfile.as_view(), name='edit_profile'),
    url(r'^me/notifications/$', views.UserNotifications.as_view(), name='my_notifications'),
    url(r'^me/$', views.ShowProfile.as_view(), name='my_profile'),
    url(r'^(?P<slug>[-\w]+)/$', views.ShowProfile.as_view(), name='show_profile'),

]

projects/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^project/(?P<pk>\d+)/apply/(?P<position>\d+)/$', views.PositionApplyView.as_view(), name='position_apply'),
    url(r'^project/(?P<pk>\d+)/delete/$', views.ProjectDeleteView.as_view(), name='project_delete'),
    url(r'^project/(?P<pk>\d+)/edit/$', views.ProjectEditView.as_view(), name='project_edit'),
    url(r'^project/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
    url(r'^project/add/$', views.ProjectCreateView.as_view(), name='add_project'),
    url(r'^$', views.ProjectListView.as_view(), name='project_list'),
]

social_team_builder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import notifications.urls


urlpatterns = [
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^users/', include('profiles.urls', namespace='profiles')),
    url(r'^me/notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^', include('projects.urls', namespace='projects')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
import os
import uuid

from django.conf import settings
from django.db import models
from django.utils.text import slugify


def avatar_upload_path(instance, filename):
    return os.path.join('avatars', 'user_{0}', '{1}').format(
        instance.user.id, filename)


class Skill(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)


class UserProject(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    profile = models.ForeignKey('UserProfile', related_name='my_projects')

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, primary_key=True, related_name='profile')
    first_name = models.CharField(max_length=50, default='')
    last_name = models.CharField(max_length=50, default='')
    slug = models.SlugField(max_length=32, unique=True, blank=True)
    has_changed_slug = models.BooleanField(default=False, editable=False)
    avatar = models.ImageField('Avatar picture',
                               upload_to=avatar_upload_path,
                               null=True,
                               blank=True)
    bio = models.TextField("Short Bio", default='')
    email_verified = models.BooleanField("Email verified", default=False)
    skills = models.ManyToManyField(Skill, blank=True, related_name='profile_skills')

    @property
    def full_name(self):
        if self.first_name:
            return '{} {}'.format(self.first_name, self.last_name)
        return '{}'.format(self.user.get_short_name())

    @property
    def get_avatar_url(self):
        if self.avatar:
            return '/media/{}'.format(self.avatar)
        return 'http://www.gravatar.com/avatar/{}?s=128&d=identicon'.format(
            '94d093eda664addd6e450d7e9881bcad'
        )

    def save(self, *args, **kwargs):
        # If no slug, generate random uuid.
        if not self.has_changed_slug:
            if self.slug or len(self.slug) >= 4:
                self.slug = self.slug
            else:
                self.slug = uuid.uuid4().hex
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return "{}'s profile".format(self.user.get_short_name())


class UserApplication(models.Model):
    applicant = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='application')
    project = models.ForeignKey('projects.Project')
    position = models.ForeignKey('projects.Position', related_name='applications')
    is_accepted = models.NullBooleanField(default=None)

    def __str__(self):
        return '{} for {}'.format(self.position, self.project)

profiles/forms.py
from django import forms

from core.forms import FormSetMedia
from . import models


class SkillForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Skill',
            'class': ''
        })
    )

    def save(self, commit=True):
        instance = super().save(commit=False)
        skill, created = models.Skill.objects.get_or_create(
            name=instance.name)
        return skill

    class Meta:
        model = models.Skill
        fields = ('name',)


class UserProjectForm(FormSetMedia):
    name = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Project Name',
            'class': ''
        })
    )
    url = forms.CharField(
        widget=forms.URLInput(attrs={
            'placeholder': 'Project URL',
            'class': ''
        })
    )

    class Meta:
        model = models.UserProject
        fields = ('name', 'url')


class UserProfileForm(FormSetMedia):
    first_name = forms.CharField(
     widget=forms.TextInput(attrs={
         'placeholder': 'First name',
         'class': ''
     })
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Last name',
            'class': ''
        })
    )
    bio = forms.CharField(
        widget=forms.Textarea(attrs={
            'placeholder': 'Tell us about yourself...',
            'class': ''
        })

    )
    avatar = forms.ImageField(
        label='Avatar',
        required=False,
        widget=forms.FileInput(attrs={
            'class': ''
        })
    )

    class Meta:
        model = models.UserProfile
        fields = ['first_name', 'last_name', 'bio', 'avatar', 'skills']


SkillInlineFormSet = forms.modelformset_factory(
    models.Skill,
    form=SkillForm,
    fields=('name',),
    extra=1,
    min_num=0,
    max_num=10
)


UserProjectInlineFormSet = forms.modelformset_factory(
    models.UserProject,
    form=UserProjectForm,
    extra=1,
    min_num=0,
    max_num=10
)

profiles/views.py
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.views import generic
from django.shortcuts import (get_object_or_404, reverse,
                              HttpResponseRedirect, Http404)
from django.contrib.auth import get_user_model

from braces.views import LoginRequiredMixin, PrefetchRelatedMixin
from dal import autocomplete
from notifications.signals import notify

from core.mixins import IsOwnerMixin
from . import forms
from . import models
from projects.models import Position

STATUS_CHOICES = {
    'new': None,
    'accepted': True,
    'rejected': False
}

User = get_user_model()


class ShowProfile(LoginRequiredMixin, PrefetchRelatedMixin, generic.TemplateView):
    model = models.UserProfile
    template_name = 'profile.html'
    context_object_name = 'profile'
    prefetch_related = [
        'my_projects', 'profile_skills',
        'user__projects__positions', 'user__projects']

    def get_context_data(self, **kwargs):
        context = super(ShowProfile, self).get_context_data(**kwargs)
        context['skills'] = context['profile'].skills.all()
        context['p_projects'] = context['profile'].user.projects.all()
        context['u_projects'] = context['profile'].my_projects.all()
        return context

    def get(self, request, **kwargs):
        slug = self.kwargs.get('slug')
        if slug:
            profile = get_object_or_404(models.UserProfile, slug=slug)
        else:
            profile = self.request.user.profile

        kwargs['profile'] = profile
        return super().get(request, **kwargs)


class EditProfile(LoginRequiredMixin, IsOwnerMixin,
                  PrefetchRelatedMixin, generic.UpdateView):
    model = models.UserProfile
    form_class = forms.UserProfileForm
    template_name = 'profile_edit.html'
    context_object_name = 'profile'
    prefetch_related = ['my_projects', 'profile_skills']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['s_formset'] = forms.SkillInlineFormSet(
            queryset=models.Skill.objects.filter(
                profile_skills=context['profile']
            ),
            prefix='skill_formset'
        )
        context['p_formset'] = forms.UserProjectInlineFormSet(
            queryset=models.UserProject.objects.filter(
                profile=context['profile']
            ),
            prefix='project_formset'
        )
        return context

    def get_object(self, queryset=None):
        obj = get_object_or_404(
            models.UserProfile,
            user=self.request.user
        )
        if obj.user != self.request.user:
            raise Http404
        return obj

    def post(self, request, *args, **kwargs):
        profile = self.get_object()
        form = forms.UserProfileForm(
            self.request.POST, request.FILES, instance=profile)
        s_formset = forms.SkillInlineFormSet(
            self.request.POST,
            queryset=models.Skill.objects.filter(
                profile_skills=profile
            ),
            prefix='skill_formset'
        )
        p_formset = forms.UserProjectInlineFormSet(
            self.request.POST,
            queryset=models.UserProject.objects.filter(
                profile=profile
            ),
            prefix='project_formset'
        )

        if form.is_valid():
            profile = form.save(commit=False)
            if s_formset.is_valid() and p_formset.is_valid():
                skills = s_formset.save()
                projects = p_formset.save(commit=False)

                for skill in skills:
                    profile.skills.add(skill)
                profile.save()

                for project in projects:
                    project.profile = profile
                    project.save()

                return HttpResponseRedirect(reverse('profiles:my_profile'))

        return HttpResponseRedirect(reverse('profiles:my_profile',
                                            {'form': form, 's_formset': s_formset}))

    def get_success_url(self):
        return reverse_lazy('profiles:show_profile', kwargs={'slug': self.object.slug})


class UserApplications(LoginRequiredMixin,
                       PrefetchRelatedMixin, generic.ListView):
    model = models.UserApplication
    template_name = 'applications.html'
    context_object_name = 'application_list'
    prefetch_related = ['applicant__projects',
                        'applicant__projects__positions']

    def get_queryset(self):
        queryset = super().get_queryset()
        status_term = self.request.GET.get('status') or 'all'
        proj_term = self.request.GET.get('proj') or 'all'
        need_term = self.request.GET.get('need') or 'all'

        if proj_term and proj_term != 'all':
            queryset = queryset.filter(
                project__title=proj_term
            )
        if need_term and need_term != 'all':
            queryset = queryset.filter(
                position__name=need_term
            )
        if status_term and status_term != 'all':
            if status_term in STATUS_CHOICES.keys():
                queryset = queryset.filter(
                    is_accepted=STATUS_CHOICES[status_term]
                )

        return queryset.filter(project__creator=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = self.request.user.projects.all()
        context['status'] = self.request.GET.get('status') or 'all'
        context['proj'] = self.request.GET.get('proj') or 'all'
        context['need'] = self.request.GET.get('need') or 'all'
        return context


class UserApplicationStatus(LoginRequiredMixin, generic.TemplateView):

    def get(self, request, *args, **kwargs):
        position_id = self.kwargs.get('position')
        position = Position.objects.filter(pk=position_id).first()
        if position.project.creator == self.request.user:
            applicant_pk = self.kwargs.get('applicant')
            applicant = get_object_or_404(User, pk=applicant_pk)
            status = self.kwargs.get('status')
            if status == 'approve' or status == 'deny':
                if position and applicant:
                    bstatus = True if status == 'approve' else False
                    application = models.UserApplication.objects.filter(
                        position=position, applicant=applicant
                    ).update(is_accepted=bstatus)

                    if status == 'approve':
                        msg_status = 'approved'
                    else:
                        msg_status = 'denied'

                    notify.send(
                        applicant,
                        recipient=applicant,
                        verb='Your application for {} as {} was {}'.format(
                            position.project.title, position.name, msg_status
                        ),
                        description=''
                    )
                    return HttpResponseRedirect(reverse('profiles:my_applications'))
        return HttpResponseRedirect(reverse('profiles:my_applications'))


class UserNotifications(LoginRequiredMixin, PrefetchRelatedMixin, generic.TemplateView):
    template_name = 'notifications.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['unreads'] = self.request.user.notifications.unread()
        return context

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

profiles/templates/applications.html
{% extends 'layouts/base.html' %}

{% block title %}Applications{% endblock %}
{% block content %}
    <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a class="selected" href="{% url 'profiles:my_applications' %}">Applications</a></li>
        <li><a href="{% url 'profiles:my_profile' %}">Profile</a></li>
      </ul>
    </nav>
    </div>

    <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>
    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
          <li><a {% if status == 'all' %}class="selected"{% endif %} href="{% url 'profiles:my_applications' %}">All Applications</a></li>
          <li><a {% if status == 'new' %}class="selected"{% endif %}href="?status=new">New Applications</a></li>
          <li><a {% if status == 'accepted' %}class="selected"{% endif %}href="?status=accepted">Accepted</a></li>
          <li><a {% if status == 'rejected' %}class="selected"{% endif %}href="?status=rejected">Rejected</a></li>
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--filter--list">
          <li><a {% if proj == 'all' %}class="selected"{% endif %}>All Projects</a></li>
            {% for project in projects %}
                <li><a {% if proj == project.title %}class="selected"{% endif %}href="?proj={{ project.title }}">{{ project }}</a></li>
            {% endfor %}
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <ul class="circle--filter--list">
            <li><a {% if need == 'all' %}class="selected"{% endif %} href="{% url 'profiles:my_applications' %}">All Needs</a></li>
        {% for project in projects %}
            {% for p_need in project.positions.all %}
                <li><a {% if p_need.name == need %}class="selected"{% endif %} href="?need={{ p_need }}">{{ p_need }}</a></li>
            {% endfor %}
        {% endfor %}
        </ul>
      </div>

    </div>
    {% if application_list %}
    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Applicant</th>
            <th class="circle--cell--right">Applicant Position</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
        {% for application in application_list %}
            <tr class="clickable-row" data-href="{% url 'profiles:show_profile' application.applicant.profile.slug %}">
                <td>
                  <h3>{{ application.applicant }}</h3>
                  <p>{{ application.project }}</p>
                </td>
                <td class="circle--cell--right">
                  <span class="secondary-label">{{ application.position }}</span>
                </td>
                {% if application.is_accepted == None %}
                    <td>
                        <a href="{% url 'profiles:status_update' application.position.pk application.applicant.pk 'approve' %}">Approve</a>
                    </td>
                    <td>
                        <a href="{% url 'profiles:status_update' application.position.pk application.applicant.pk 'deny' %}">Deny</a>
                    </td>

                {% elif application.is_accepted %}
                    <td colspan="2">Approved!</td>
                {% elif not application.is_accepted %}
                    <td colspan="2">Denied</td>
                {% endif %}


            </tr>
        {% endfor %}
        </tbody>
      </table>

    </div>

    {% else %}
    <div class="grid-70 grid-push-5">
        <h3>You have no applications or you have not created a project.</h3>
    </div>
    {% endif %}
    </div>
{% endblock %}

profiles/templates/notifications.html
{% extends 'layouts/base.html' %}
{% load humanize %}
{% block title %}My Notifications{% endblock %}
{% block content %}

<div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
          <h2>Recent Notifications</h2>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">

    <div class="grid-70">

      <div class="circle--article--body">
      {% if unreads %}
        {% for message in unreads %}
            <p>{{ message.verb }}</p>
            <p><strong>{{ message.timestamp|naturaltime }}</strong></p>
            <hr/>
          {% endfor %}
      {% else %}
          <p>No messages to display.</p>
      {% endif %}
      </div>
    </div>

  </div>
{% endblock %}

profiles/templates/profile.html
{% extends 'layouts/base.html' %}

{% block title %}Profile{% endblock %}
{% block content %}

<div class="circle--actions--bar">
{% if user.is_authenticated and request.user == profile.user %}
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="{% url 'profiles:my_applications' %}">Applications</a></li>
        <li><a class="" href="{% url 'profiles:my_profile' %}">Profile</a></li>

      </ul>
    </nav>
{% endif %}
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Profile</h2>
      </div>
        {% if user.is_authenticated and request.user == profile.user %}
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button icon-on-left" href="{% url 'profiles:edit_profile' %}">Edit</a>
      </div>
        {% endif %}
    </div>

    <div class="grid-70">
      <h1>{{ profile.full_name }}</h1>
      <div class="circle--article--body">
        {{ profile.bio }}
      </div>

      <h2>Past Projects</h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
        {% if p_projects %}
          {% for project in p_projects %}
            <tr class="clickable-row" data-href="{% url 'projects:project_detail' project.pk %}">
              <td>
                <h3>{{ project.title }}</h3>
              </td>
              <td class="circle--cell--right">
                <span class="secondary-label">
                  {% if project.positions.all %}
                      {{ project.positions.all|join:", " }}
                  {% else %}
                    N/A
                  {% endif %}
                </span>
              </td>
            </tr>
          {% endfor %}
        {% endif %}
        </tbody>
      </table>

    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <!-- Placeholder Gravatar -->
          <img src="{{ profile.get_avatar_url }}" alt="Avatar" width="100%">
      </div>

      <div class="circle--secondary--module">
        <h4>My Skills</h4>
        <ul class="unloaded">
          {% if skills %}

            {% for skill in skills %}
              <li>{{ skill }}</li>
            {% endfor %}
          {% else %}
            <li>N/A</li>
          {% endif %}
        </ul>
      </div>

      <div class="circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--link--list">
          {% if u_projects %}
            {% for project in u_projects %}
              <li><a href="{{ project.url }}" target="_blank">{{ project.name }}</a></li>
            {% endfor %}
          {% else %}
            <li>N/A</li>
          {% endif %}
        </ul>
      </div>
    </div>

  </div>
{% endblock %}

profiles/templates/profile_edit.html
{% extends 'layouts/base.html' %}

{% block title %}Edit Profile{% endblock %}
{% block content %}

<div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="{% url 'profiles:my_applications' %}">Applications</a></li>
        <li><a class="selected" href="{% url 'profiles:my_profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
  <form action="" method="POST" enctype="multipart/form-data">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Profile</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <button class="button button-primary icon-on-left" type="submit">Save Changes</button>
      </div>
    </div>

        {% csrf_token %}

        <div class="grid-70">
            {{ form.first_name }}
            {{ form.last_name }}
            {{ form.bio }}

        </div>
        <div class="grid-25 grid-push-5">
          <div class="circle--secondary--module">

                <img src="{{ profile.get_avatar_url }}" alt="Avatar" width="100%">
            {{ form.avatar }}
          </div>
          <div class="circle--secondary--module">
            <h4>My Skills</h4>
            <ul class="circle--group circle--list">
                {{ s_formset.management_form }}
                {% for s_form in s_formset %}
                  <li class="skill-formset">
                    {{ s_form.id }}
                    {{ s_form.name }}
                  </li>
                {% endfor %}
            </ul>
          </div>
          <div class="circle--secondary--module">
            <h4>My Projects</h4>
            <ul class="circle--group circle--list">
                {{ p_formset.management_form }}
                {% for p_form in p_formset %}
              <li class="project-formset">
                {{ p_form.id }}
                {{ p_form.name }}
                {{ p_form.url }}
              </li>
                {% endfor %}
            </ul>
          </div>
        </div>
    </form>
  </div>

</div>

{% endblock %}

{% block js %}
    {% load static from staticfiles %}
    {{ form.media.js }}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script>
        $('.skill-formset').formset({
            prefix: '{{ s_formset.prefix }}',
            addText: 'Add skill',
            deleteText: 'Remove'
        });
        $('.project-formset').formset({
                prefix: '{{ p_formset.prefix }}',
                addText: 'Add Project',
                deleteText: 'Remove'
            });
    </script>
{% endblock js %}