accounts/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
]

profiles/urls.py
from django.conf.urls import url, include


from . import views


urlpatterns = [
    url(r'^me/applications/(?P<position>\d+)/(?P<applicant>\d+)/(?P<status>\w+)/$',
        views.UserApplicationStatus.as_view(), name='status_update'),
    url(r'^me/applications/$', views.UserApplications.as_view(), name='my_applications'),
    url(r'^me/edit/$', views.EditProfile.as_view(), name='edit_profile'),
    url(r'^me/notifications/$', views.UserNotifications.as_view(), name='my_notifications'),
    url(r'^me/$', views.ShowProfile.as_view(), name='my_profile'),
    url(r'^(?P<slug>[-\w]+)/$', views.ShowProfile.as_view(), name='show_profile'),

]

projects/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^project/(?P<pk>\d+)/apply/(?P<position>\d+)/$', views.PositionApplyView.as_view(), name='position_apply'),
    url(r'^project/(?P<pk>\d+)/delete/$', views.ProjectDeleteView.as_view(), name='project_delete'),
    url(r'^project/(?P<pk>\d+)/edit/$', views.ProjectEditView.as_view(), name='project_edit'),
    url(r'^project/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
    url(r'^project/add/$', views.ProjectCreateView.as_view(), name='add_project'),
    url(r'^$', views.ProjectListView.as_view(), name='project_list'),
]

social_team_builder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import notifications.urls


urlpatterns = [
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^users/', include('profiles.urls', namespace='profiles')),
    url(r'^me/notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^', include('projects.urls', namespace='projects')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from django.conf import settings

from profiles.models import Skill


class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(default='')
    requirements = models.TextField(default='')
    timeline = models.CharField(max_length=255, blank=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                related_name='projects', null=True)

    @property
    def open_positions(self):
        return self.positions.exclude(applications__is_accepted=True)

    def __str__(self):
        return '{}'.format(self.title)


class Position(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(default='')
    project = models.ForeignKey(Project, related_name='positions')
    skills = models.ManyToManyField(Skill, related_name='related_skills')

    def __str__(self):
        return '{}'.format(self.name)

projects/forms.py
from django import forms

from core.forms import FormSetMedia
from profiles.models import Skill
from . import models


class ProjectCreateForm(FormSetMedia):
    title = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Project Title',
                'class': 'circle--input--h1'
            })
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Project description...'})
    )
    requirements = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': ''})
    )
    timeline = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Time estimate',
                'class': 'circle--textarea--input'
            })
    )

    class Meta:
        model = models.Project
        fields = ('title', 'description', 'requirements', 'timeline')


class PositionCreateForm(FormSetMedia):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Position Title',
                'class': ''
            }
        )
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Position description...',
                'class': ''
            }
        )
    )
    skills = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        queryset=Skill.objects.all()
    )

    class Meta:
        model = models.Position
        fields = ('name', 'description', 'skills')


PositionFormSet = forms.modelform_factory(
    models.Position,
    form=PositionCreateForm
)

PositionInlineFormSet = forms.modelformset_factory(
    models.Position,
    form=PositionCreateForm,
    fields=('name', 'description', 'skills'),
    extra=0,
    min_num=1,
    max_num=8
)

projects/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, reverse, Http404
from django.urls import reverse_lazy
from django.views import generic
from django.db.models import Q

from notifications.signals import notify

from braces.views import LoginRequiredMixin, PrefetchRelatedMixin

from core.mixins import IsOwnerMixin
from . import forms
from . import models
from profiles.models import UserApplication


class ProjectListView(PrefetchRelatedMixin, generic.ListView):
    model = models.Project
    template_name = 'project_list.html'
    context_object_name = 'projects'
    prefetch_related = ['positions', 'positions__skills']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project_needs'] = models.Position.objects.filter(
            project__in=context['projects']
        ).exclude(applications__is_accepted=True)

        context['skill_needs'] = models.Skill.objects.filter(
            related_skills__in=context['project_needs']
        ).distinct()
        context['curr_filter'] = self.request.GET.get('filter')
        context['curr_term'] = self.request.GET.get('s')
        context['curr_skill'] = self.request.GET.get('skill')
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        search_term = self.request.GET.get('s')
        if search_term:
            queryset = queryset.filter(
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term)
            )
        filter_term = self.request.GET.get('filter')
        if filter_term:
            queryset = queryset.filter(
                Q(positions__name=filter_term)
            )

        skill_term = self.request.GET.get('skill')
        if skill_term:
            queryset = queryset.filter(
                positions__skills__name=skill_term
            ).distinct()

        return queryset


class ProjectDetailView(LoginRequiredMixin, PrefetchRelatedMixin, generic.DetailView):
    model = models.Project
    template_name = 'project_detail.html'
    context_object_name = 'project'
    prefetch_related = ['creator__profile', 'positions', 'positions__applications']

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        context['profile'] = context['project'].creator.profile
        context['positions'] = models.Position.objects.filter(
            project=context['project']).exclude(applications__is_accepted=True)
        context['applied_for'] = models.Position.objects.filter(
            project=context['project'],
            applications__applicant=self.request.user)
        return context


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = models.Project
    form_class = forms.ProjectCreateForm
    template_name = 'project_create.html'
    success_url = reverse_lazy('projects:project_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['p_formset'] = forms.PositionInlineFormSet(
            queryset=models.Position.objects.none(),
            prefix='p_formset'
        )
        return context

    def post(self, request, *args, **kwargs):
        form = forms.ProjectCreateForm(self.request.POST)
        p_formset = forms.PositionInlineFormSet(
            self.request.POST,
            queryset=models.Position.objects.none(),
            prefix='p_formset'
        )

        if form.is_valid():
            project = form.save(commit=False)
            project.creator = self.request.user
            project.save()
            if p_formset.is_valid():
                positions = p_formset.save(commit=False)
                for position in positions:
                    position.project = project
                    position.save()
                p_formset.save_m2m()
        return HttpResponseRedirect(reverse('projects:project_list'))


class ProjectEditView(LoginRequiredMixin, IsOwnerMixin, generic.UpdateView):
    model = models.Project
    form_class = forms.ProjectCreateForm
    template_name = 'project_edit.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['p_formset'] = forms.PositionInlineFormSet(
            queryset=models.Position.objects.filter(project=context['project']),
            prefix='p_formset'
        )
        return context


class ProjectDeleteView(LoginRequiredMixin, IsOwnerMixin, generic.DeleteView):
    model = models.Project
    form_class = forms.ProjectCreateForm
    context_object_name = 'project'
    template_name = 'project_delete.html'
    success_url = reverse_lazy('projects:project_list')

    def get_object(self, queryset=None):
        obj = super().get_object()
        if not obj.creator == self.request.user:
            raise Http404
        return obj


class PositionApplyView(LoginRequiredMixin, generic.TemplateView):

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        pos_pk = self.kwargs.get('position')
        project = get_object_or_404(models.Project, pk=pk)
        position = get_object_or_404(models.Position, pk=pos_pk)
        application = UserApplication.objects.filter(
            position=position,
            applicant=self.request.user
        )

        if application.exists():
            return HttpResponseRedirect(reverse(
                   'projects:project_detail', kwargs={'pk': pk}))

        UserApplication.objects.create(
            applicant=self.request.user,
            project=project,
            position=position
        )

        notify.send(
            self.request.user,
            recipient=self.request.user,
            verb='YOU submitted an application for {} as {}.'.format(
              project.title, position.name
            ),
            description=''
        )
        notify.send(
            project.creator,
            recipient=project.creator,
            verb='{} submitted an application for {} as {}'.format(
                self.request.user, project.title, position.name,
            ),
            description=''
        )
        return HttpResponseRedirect(reverse(
            'projects:project_list'))

projects/templates/project_create.html
{% extends 'layouts/base.html' %}

{% block title %}{{ block.super }}{% endblock %}

  {% block content %}
<form action="" method="POST">
    {% csrf_token %}
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <button class="button button-primary" type="submit">Save Project</button>
        <a class="button button-text" href="{% url 'projects:project_list' %}">Discard</a>
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--body">
          {{ form.title.errors }}
          {{ form.title }}
          {{ form.description }}
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>

        <ul class="circle--group--list circle--list">
            {{ p_formset.management_form }}
            {% for p_form in p_formset %}

            <li class="p-formset">
                {{ p_form.name }}
                {{ p_form.description }}
                {% for skill in p_form.skills %}
                    {{ skill }}
                {% endfor %}
            </li>

            {% endfor %}
        </ul>

        <button class="button button-primary" type="submit">Save Project</button>

      </div>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
          {{ form.timeline.errors }}
          {{ form.timeline }}

      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
          {{ form.requirements.errors }}
          {{ form.requirements }}
      </div>
    </div>
  </div>
</form>
{% endblock %}

{% block js %}
    {% load static from staticfiles %}
    {{ form.media.js }}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script>
        $('.p-formset').formset({
            prefix: '{{ p_formset.prefix }}',
            addText: 'Add position',
            deleteText: 'Remove'
        });
    </script>
{% endblock js %}

projects/templates/project_delete.html
{% extends 'layouts/base.html' %}

{% block title %}{{ project }} Confirm Delete{% endblock %}

  {% block content %}
<div class="bounds circle--page circle--article">
    <div class="grid-70">
    <form action="" method="POST">
        {% csrf_token %}
        <h4>Are you sure you want to delete {{ project }}?</h4>
        <p>This cannot be undone.</p>
        <div class="grid-30">
            <button class="button button-primary" type="submit">Yes</button>
        </div>
        <div class="grid-30"></div>
        <div class="grid-30">
            <a class="button button-secondary" href="{% url 'projects:project_list' %}">No</a>
        </div>
    </form>
    </div>
</div>
{% endblock %}

projects/templates/project_detail.html
{% extends 'layouts/base.html' %}

{% block title %}{{ block.super }}{% endblock %}
{% block content %}

{% if user.is_authenticated and user == project.creator %}
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <a class="button" href="{% url 'projects:project_edit' project.pk %}">Edit Project</a>
        <a class="button button-text" href="{% url 'projects:project_delete' project.pk %}">Delete Project</a>
      </div>
    </div>
  </div>
{% endif %}

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--header">
        <h4 class="circle--article--section">Project</h4>
        <h1 class="circle--article--title">{{ project.title }}</h1>
        <p class="circle--article--byline">Project Owner: <a href="{% url 'profiles:show_profile' profile.slug %}">{{ profile.full_name }}</a></p>
      </div>

      <div class="circle--article--body">
        {{ project.description }}
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>
        <ul class="circle--group--list">
        {% if not positions %}
        <li>There are no OPEN positions on this project.</li>
        {% else %}
          {% for position in positions %}
          <li>
            <h3>{{ position.name }}</h3>
            <p>{{ position.description }}</p>
          {% if position in applied_for %}
              <button disabled class="button button-inactive">Already Applied</button>
          {% else %}
            <a class="button button-primary" href="{% url 'projects:position_apply' position.project.pk position.pk %}">Apply</a>
          {% endif %}
          </li>
          {% endfor %}
        {% endif %}
        </ul>
      </div>

    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        <p>{{ project.timeline }}</p>
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        <p>{{ project.requirements }}</p>
      </div>

    </div>
  </div>

{% endblock %}

projects/templates/project_edit.html
{% extends 'layouts/base.html' %}

{% block title %}{{ block.super }}{% endblock %}

  {% block content %}
<form action="" method="POST">
    {% csrf_token %}
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <button class="button button-primary" type="submit">Save changes</button>
        <a class="button button-text" href="{% url 'projects:project_delete' project.pk %}">Delete project</a>
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--body">
          {{ form.title.errors }}
          {{ form.title }}
          {{ form.description }}
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>

        <ul class="circle--group--list circle--list">
            {{ p_formset.management_form }}
            {% for p_form in p_formset %}

            <li class="p-formset">
                {{ p_form.name }}
                {{ p_form.description }}
            {% for skill in p_form.skills %}
                    {{ skill }}
            {% endfor %}
            </li>
            {% endfor %}
        </ul>

        <button class="button button-primary" type="submit">Save changes</button>

      </div>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
          {{ form.timeline.errors }}
          {{ form.timeline }}

      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
          {{ form.requirements.errors }}
          {{ form.requirements }}
      </div>
    </div>
  </div>
</form>
{% endblock %}

{% block js %}
    {% load static from staticfiles %}
    {{ form.media.js }}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script>
        $('.p-formset').formset({
            prefix: '{{ p_formset.prefix }}',
            addText: 'Add position',
            deleteText: 'Remove'
        });
    </script>
{% endblock js %}

projects/templates/project_list.html
{% extends 'layouts/base.html' %}

{% block title %}{{ block.super }}{% endblock %}
  {% block content %}
  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Projects</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button button-primary icon-on-left" href="{% url 'projects:add_project' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
            <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
          </svg>
          New Project
        </a>
      </div>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <ul class="circle--filter--list">
          {% if project_needs %}
            <li><a href="{% url 'projects:project_list' %}" {% if not curr_filter %}class="selected"{% endif %}>All Needs</a></li>
            {% for position in project_needs %}
              <li><a href="?filter={{ position.name }}"{% if curr_filter == position.name %}class="selected"{% endif %}>{{ position.name }}</a></li>
            {% endfor %}
          {% else %}
            <li>N/A</li>
          {% endif %}
        </ul>
      </div>
        <div class="circle--filter circle--secondary--module">
        <h4>By Skills</h4>
        <ul class="circle--filter--list">
          {% if skill_needs %}
            <li><a href="{% url 'projects:project_list' %}" {% if not curr_skill %}class="selected"{% endif %}>All Needs</a></li>
          {% for skill in skill_needs %}
              <li><a href="?skill={{ skill.name }}"{% if curr_skill == skill.name %}class="selected"{% endif %}>{{ skill.name }}</a></li>
          {% endfor %}
          {% else %}
            <li>N/A</li>
          {% endif %}
        </ul>
      </div>
    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
        {% for project in projects %}
            <tr class="clickable-row" data-href="{% url 'projects:project_detail' project.pk %}">
                <td>
                  <h3>{{ project.title }}</h3>
                </td>
                <td class="circle--cell--right">

                  <span class="secondary-label">{% if project.open_positions %}
                      {{ project.open_positions|join:", " }}
                      {% else %}No open positions
                      {% endif %}
                      </span>
                </td>
            </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% endblock %}
</body>
</html>