accounts/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
]

profiles/urls.py
from django.conf.urls import url, include


from . import views


urlpatterns = [
    url(r'^me/applications/(?P<position>\d+)/(?P<applicant>\d+)/(?P<status>\w+)/$',
        views.UserApplicationStatus.as_view(), name='status_update'),
    url(r'^me/applications/$', views.UserApplications.as_view(), name='my_applications'),
    url(r'^me/edit/$', views.EditProfile.as_view(), name='edit_profile'),
    url(r'^me/notifications/$', views.UserNotifications.as_view(), name='my_notifications'),
    url(r'^me/$', views.ShowProfile.as_view(), name='my_profile'),
    url(r'^(?P<slug>[-\w]+)/$', views.ShowProfile.as_view(), name='show_profile'),

]

projects/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^project/(?P<pk>\d+)/apply/(?P<position>\d+)/$', views.PositionApplyView.as_view(), name='position_apply'),
    url(r'^project/(?P<pk>\d+)/delete/$', views.ProjectDeleteView.as_view(), name='project_delete'),
    url(r'^project/(?P<pk>\d+)/edit/$', views.ProjectEditView.as_view(), name='project_edit'),
    url(r'^project/(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
    url(r'^project/add/$', views.ProjectCreateView.as_view(), name='add_project'),
    url(r'^$', views.ProjectListView.as_view(), name='project_list'),
]

social_team_builder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import notifications.urls


urlpatterns = [
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^users/', include('profiles.urls', namespace='profiles')),
    url(r'^me/notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^', include('projects.urls', namespace='projects')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms


class FormSetMedia(forms.ModelForm):
    class Media:
        js = (
            'js/jquery.formset.js',
        )

core/views.py
from django.views import generic


class HomepageView(generic.TemplateView):
    template_name = 'index.html'

core/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>{% block title %}Home{% endblock %} | ST Builder</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static 'css/global.css' %}">

    {% block css %}{% endblock %}


</head>
<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'projects:project_list' %}">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <form action="{% url 'projects:project_list' %}" method="GET">
              <input type="text" name="s" value="{{ search_term }}" placeholder="Search Projects..." />
              <button>
                <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                  <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                  C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
                </svg>
              </button>
            </form>


          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
				{% if user.is_authenticated %}
                    <li><a href="{% url 'profiles:my_notifications' %}">Notifications</a></li>
					<li><a href="{% url 'profiles:my_profile' %}">My Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>

				{% else %}
					<li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
					<li><a href="{% url 'accounts:login' %}">Sign In</a></li>
				{% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
    {% block content %}{% endblock %}

      <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript" src="{% static 'js/autogrow.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/global.js' %}"></script>
    {% block js %}{% endblock js %}
</body>
</html>